# Generated by Django 5.2.1 on 2025-05-22 05:42

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("app", "0002_studenttest_is_completed_and_more"),
    ]

    operations = [
        migrations.AddField(
            model_name="student",
            name="course",
            field=models.CharField(blank=True, max_length=50, null=True),
        ),
        migrations.AddField(
            model_name="student",
            name="group",
            field=models.CharField(blank=True, max_length=50, null=True),
        ),
        migrations.AddField(
            model_name="test",
            name="group",
            field=models.CharField(blank=True, max_length=50, null=True),
        ),
    ]
